{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{ "major" : 9, "minor" : 1, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
		"classnamespace" : "box",
		"rect" : [ 40.0, 40.0, 1400.0, 880.0 ],
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"boxes" : [
			{ "box" : { "id" : "in-bins", "maxclass" : "inlet", "numinlets":0, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 20.0, 30.0, 30.0 ], "comment" : "8-bin list (post organic-mod) - triggers voice envelopes" } },
			{ "box" : { "id" : "in-frame", "maxclass" : "inlet", "numinlets":0, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 80.0, 20.0, 30.0, 30.0 ], "comment" : "frame bang (from jit.world)" } },
			{ "box" : { "id" : "in-pulse", "maxclass" : "inlet", "numinlets":0, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 130.0, 20.0, 30.0, 30.0 ], "comment" : "biological pulse 0..1 (drives displacement LFO)" } },

			{ "box" : { "id" : "out-pos", "maxclass" : "outlet", "numinlets":1, "numoutlets":0,
				"patching_rect" : [ 30.0, 820.0, 30.0, 30.0 ], "comment" : "jit_matrix vertex positions (feed to jit.gl.mesh)" } },
			{ "box" : { "id" : "out-nrm", "maxclass" : "outlet", "numinlets":1, "numoutlets":0,
				"patching_rect" : [ 80.0, 820.0, 30.0, 30.0 ], "comment" : "jit_matrix vertex normals" } },
			{ "box" : { "id" : "out-info", "maxclass" : "outlet", "numinlets":1, "numoutlets":0,
				"patching_rect" : [ 130.0, 820.0, 30.0, 30.0 ], "comment" : "info messages" } },

			{ "box" : { "id" : "title", "maxclass" : "comment",
				"patching_rect" : [ 30.0, 55.0, 1300.0, 22.0 ], "fontsize" : 14.0,
				"text" : "fh.mesh_synth : audio-driven 3D modelling instrument.  Voices (SDF primitives) → 3D voxel field → marching cubes → mesh + export.",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "lbl-voices", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 90.0, 640.0, 20.0 ], "text" : "VOICES  (8x SDF oscillator - waveshape / xyz / radius)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "voice-preset", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 115.0, 640.0, 22.0 ],
				"text" : "voices 0.30 0.20 0.30 0 0.18 0.50 0.20 0.50 0 0.20 0.70 0.20 0.70 0 0.18 0.20 0.50 0.50 2 0.16 0.80 0.50 0.50 2 0.16 0.30 0.80 0.30 1 0.14 0.70 0.80 0.70 1 0.14 0.50 0.55 0.50 5 0.28" } },

			{ "box" : { "id" : "voice-preset-load", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 680.0, 115.0, 80.0, 22.0 ], "text" : "loadbang" } },

			{ "box" : { "id" : "voice-tap-1", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 145.0, 220.0, 22.0 ], "text" : "shape 7 5", "comment" : "voice 8 -> gyroid" } },
			{ "box" : { "id" : "voice-tap-2", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 260.0, 145.0, 220.0, 22.0 ], "text" : "voice 0 0.15 0.5 0.5 4 0.20" } },
			{ "box" : { "id" : "voice-tap-3", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 490.0, 145.0, 220.0, 22.0 ], "text" : "voice 7 0.5 0.5 0.5 3 0.22" } },

			{ "box" : { "id" : "lbl-env", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 180.0, 640.0, 20.0 ], "text" : "ENVELOPES  (per-voice ADSR - shared with the fluid injector)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "organic-mod", "maxclass" : "newobj",
				"patching_rect" : [ 30.0, 205.0, 640.0, 22.0 ],
				"text" : "fh.organic_mod",
				"numinlets":3, "numoutlets":1, "outlettype":[""] } },

			{ "box" : { "id" : "lbl-field", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 245.0, 640.0, 20.0 ], "text" : "3D VOXEL FIELD  (48^3 float32 - decay + splat + smooth per frame)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "voxel-field", "maxclass" : "newobj",
				"patching_rect" : [ 30.0, 270.0, 640.0, 22.0 ],
				"text" : "fh.voxel_field",
				"numinlets":5, "numoutlets":2, "outlettype":["jit_matrix",""] } },

			{ "box" : { "id" : "decay-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 30.0, 295.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "decay",
					"parameter_shortname" : "decay", "parameter_initial" : [ 0.94 ],
					"parameter_range" : [ 0.5, 0.999 ] } } } },
			{ "box" : { "id" : "blur-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 140.0, 295.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "blur",
					"parameter_shortname" : "blur", "parameter_initial" : [ 0.25 ],
					"parameter_range" : [ 0.0, 1.0 ] } } } },

			{ "box" : { "id" : "lbl-mc", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 335.0, 640.0, 20.0 ], "text" : "MARCHING CUBES  (threshold = filter cutoff)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "mc-js", "maxclass" : "newobj", "numinlets":1, "numoutlets":4,
				"outlettype":["jit_matrix","jit_matrix","",""],
				"patching_rect" : [ 30.0, 360.0, 640.0, 22.0 ], "text" : "js marching_cubes.js" } },

			{ "box" : { "id" : "threshold-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 30.0, 385.0, 200.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "threshold",
					"parameter_shortname" : "cutoff", "parameter_initial" : [ 0.4 ],
					"parameter_range" : [ 0.05, 1.5 ] } } } },
			{ "box" : { "id" : "threshold-msg", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 240.0, 385.0, 130.0, 22.0 ], "text" : "prepend threshold" } },

			{ "box" : { "id" : "lbl-shade", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 425.0, 640.0, 20.0 ], "text" : "MESH SHADER  (vertex noise displacement + heat LUT)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "mesh", "maxclass" : "newobj",
				"patching_rect" : [ 30.0, 450.0, 640.0, 22.0 ],
				"text" : "jit.gl.mesh fh @draw_mode triangles @color 1. 1. 1. 1. @lighting_enable 0",
				"numinlets":1, "numoutlets":1, "outlettype":[""] } },

			{ "box" : { "id" : "mesh-shader", "maxclass" : "newobj",
				"patching_rect" : [ 30.0, 480.0, 640.0, 22.0 ],
				"text" : "jit.gl.shader fh @file shaders/fh.mesh_shade.jxs",
				"numinlets":1, "numoutlets":1, "outlettype":[""] } },

			{ "box" : { "id" : "shader-bind", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 680.0, 480.0, 220.0, 22.0 ], "text" : "shader fh_mesh_shade" } },

			{ "box" : { "id" : "displace-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 30.0, 505.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "displace",
					"parameter_shortname" : "disp", "parameter_initial" : [ 0.12 ],
					"parameter_range" : [ 0.0, 0.6 ] } } } },
			{ "box" : { "id" : "noise-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 140.0, 505.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "noise_scale",
					"parameter_shortname" : "noise", "parameter_initial" : [ 3.0 ],
					"parameter_range" : [ 0.5, 12.0 ] } } } },
			{ "box" : { "id" : "organic-bias", "maxclass" : "live.slider",
				"patching_rect" : [ 250.0, 505.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "organic_bias",
					"parameter_shortname" : "org", "parameter_initial" : [ 0.35 ],
					"parameter_range" : [ 0.0, 1.0 ] } } } },
			{ "box" : { "id" : "rim-slider", "maxclass" : "live.slider",
				"patching_rect" : [ 360.0, 505.0, 100.0, 20.0 ],
				"parameter_enable":1, "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"saved_attribute_attributes" : { "valueof" : { "parameter_longname" : "rim",
					"parameter_shortname" : "rim", "parameter_initial" : [ 0.35 ],
					"parameter_range" : [ 0.0, 2.0 ] } } } },

			{ "box" : { "id" : "prep-displace", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 530.0, 160.0, 22.0 ], "text" : "prepend param displace" } },
			{ "box" : { "id" : "prep-noise", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 200.0, 530.0, 160.0, 22.0 ], "text" : "prepend param noise_scale" } },
			{ "box" : { "id" : "prep-org", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 370.0, 530.0, 160.0, 22.0 ], "text" : "prepend param organic_bias" } },
			{ "box" : { "id" : "prep-rim", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 540.0, 530.0, 160.0, 22.0 ], "text" : "prepend param rim" } },
			{ "box" : { "id" : "prep-pulse", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 710.0, 530.0, 160.0, 22.0 ], "text" : "prepend param pulse" } },

			{ "box" : { "id" : "lbl-export", "maxclass" : "comment", "fontface":1,
				"patching_rect" : [ 30.0, 570.0, 640.0, 20.0 ], "text" : "FREEZE + EXPORT",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "freeze-tgl", "maxclass" : "toggle",
				"patching_rect" : [ 30.0, 595.0, 30.0, 30.0 ], "numinlets":1, "numoutlets":1, "outlettype":["int"] } },
			{ "box" : { "id" : "freeze-msg", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 70.0, 600.0, 100.0, 22.0 ], "text" : "sel 0 1" } },
			{ "box" : { "id" : "freeze-gate", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 630.0, 60.0, 22.0 ], "text" : "gate 1 1" } },
			{ "box" : { "id" : "freeze-lbl", "maxclass" : "comment",
				"patching_rect" : [ 65.0, 595.0, 200.0, 20.0 ], "text" : "hold current mesh (stop updates)",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "exp-js", "maxclass" : "newobj", "numinlets":1, "numoutlets":2, "outlettype":["",""],
				"patching_rect" : [ 30.0, 690.0, 220.0, 22.0 ], "text" : "js mesh_export.js" } },

			{ "box" : { "id" : "exp-pos-msg", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 260.0, 690.0, 160.0, 22.0 ], "text" : "prepend position" } },
			{ "box" : { "id" : "exp-nrm-msg", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 430.0, 690.0, 160.0, 22.0 ], "text" : "prepend normal" } },

			{ "box" : { "id" : "exp-obj-btn", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 725.0, 60.0, 22.0 ], "text" : "obj" } },
			{ "box" : { "id" : "exp-stl-btn", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 100.0, 725.0, 60.0, 22.0 ], "text" : "stl" } },
			{ "box" : { "id" : "exp-ply-btn", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 170.0, 725.0, 60.0, 22.0 ], "text" : "ply" } },
			{ "box" : { "id" : "exp-all-btn", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 240.0, 725.0, 60.0, 22.0 ], "text" : "all" } },
			{ "box" : { "id" : "exp-dir-msg", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 310.0, 725.0, 300.0, 22.0 ], "text" : "dir ~/ExternalRadio/fh_meshes" } },

			{ "box" : { "id" : "cmt-instrument", "maxclass" : "comment",
				"patching_rect" : [ 30.0, 760.0, 1300.0, 45.0 ],
				"text" : "Instrument mapping: 8 audio bins → 8 voice ADSR envelopes → SDF splats in voxel field → marching-cubes isosurface at threshold (cutoff) → noise-displaced mesh in heat palette → freeze + export OBJ / STL / PLY.  Load exports into Blender, Cinema4D, Houdini, Unreal, etc." } },

			{ "box" : { "id" : "frame-time", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":["float"],
				"patching_rect" : [ 900.0, 20.0, 100.0, 22.0 ], "text" : "cpuclock" } },
			{ "box" : { "id" : "time-msg", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 1010.0, 20.0, 200.0, 22.0 ], "text" : "prepend param time" } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "voice-preset-load", 0 ], "destination" : [ "voice-preset", 0 ] } },
			{ "patchline" : { "source" : [ "voice-preset", 0 ], "destination" : [ "voxel-field", 2 ] } },
			{ "patchline" : { "source" : [ "voice-tap-1", 0 ], "destination" : [ "voxel-field", 2 ] } },
			{ "patchline" : { "source" : [ "voice-tap-2", 0 ], "destination" : [ "voxel-field", 2 ] } },
			{ "patchline" : { "source" : [ "voice-tap-3", 0 ], "destination" : [ "voxel-field", 2 ] } },

			{ "patchline" : { "source" : [ "in-bins", 0 ], "destination" : [ "organic-mod", 0 ] } },
			{ "patchline" : { "source" : [ "organic-mod", 0 ], "destination" : [ "voxel-field", 1 ] } },
			{ "patchline" : { "source" : [ "in-frame", 0 ], "destination" : [ "voxel-field", 0 ] } },
			{ "patchline" : { "source" : [ "decay-slider", 0 ], "destination" : [ "voxel-field", 3 ] } },
			{ "patchline" : { "source" : [ "blur-slider", 0 ], "destination" : [ "voxel-field", 4 ] } },

			{ "patchline" : { "source" : [ "voxel-field", 0 ], "destination" : [ "freeze-gate", 1 ] } },
			{ "patchline" : { "source" : [ "freeze-tgl", 0 ], "destination" : [ "freeze-msg", 0 ] } },
			{ "patchline" : { "source" : [ "freeze-msg", 0 ], "destination" : [ "freeze-gate", 0 ] } },
			{ "patchline" : { "source" : [ "freeze-gate", 0 ], "destination" : [ "mc-js", 0 ] } },

			{ "patchline" : { "source" : [ "threshold-slider", 0 ], "destination" : [ "threshold-msg", 0 ] } },
			{ "patchline" : { "source" : [ "threshold-msg", 0 ], "destination" : [ "mc-js", 0 ] } },

			{ "patchline" : { "source" : [ "mc-js", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "mc-js", 0 ], "destination" : [ "out-pos", 0 ] } },
			{ "patchline" : { "source" : [ "mc-js", 1 ], "destination" : [ "out-nrm", 0 ] } },
			{ "patchline" : { "source" : [ "mc-js", 2 ], "destination" : [ "out-info", 0 ] } },
			{ "patchline" : { "source" : [ "mc-js", 3 ], "destination" : [ "out-info", 0 ] } },

			{ "patchline" : { "source" : [ "shader-bind", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "mesh-shader", 0 ], "destination" : [ "mesh", 0 ] } },

			{ "patchline" : { "source" : [ "displace-slider", 0 ], "destination" : [ "prep-displace", 0 ] } },
			{ "patchline" : { "source" : [ "prep-displace", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "noise-slider", 0 ], "destination" : [ "prep-noise", 0 ] } },
			{ "patchline" : { "source" : [ "prep-noise", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "organic-bias", 0 ], "destination" : [ "prep-org", 0 ] } },
			{ "patchline" : { "source" : [ "prep-org", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "rim-slider", 0 ], "destination" : [ "prep-rim", 0 ] } },
			{ "patchline" : { "source" : [ "prep-rim", 0 ], "destination" : [ "mesh", 0 ] } },
			{ "patchline" : { "source" : [ "in-pulse", 0 ], "destination" : [ "prep-pulse", 0 ] } },
			{ "patchline" : { "source" : [ "prep-pulse", 0 ], "destination" : [ "mesh", 0 ] } },

			{ "patchline" : { "source" : [ "in-frame", 0 ], "destination" : [ "frame-time", 0 ] } },
			{ "patchline" : { "source" : [ "frame-time", 0 ], "destination" : [ "time-msg", 0 ] } },
			{ "patchline" : { "source" : [ "time-msg", 0 ], "destination" : [ "mesh", 0 ] } },

			{ "patchline" : { "source" : [ "mc-js", 0 ], "destination" : [ "exp-pos-msg", 0 ] } },
			{ "patchline" : { "source" : [ "exp-pos-msg", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "mc-js", 1 ], "destination" : [ "exp-nrm-msg", 0 ] } },
			{ "patchline" : { "source" : [ "exp-nrm-msg", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-dir-msg", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-obj-btn", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-stl-btn", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-ply-btn", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-all-btn", 0 ], "destination" : [ "exp-js", 0 ] } },
			{ "patchline" : { "source" : [ "exp-js", 0 ], "destination" : [ "out-info", 0 ] } },
			{ "patchline" : { "source" : [ "exp-js", 1 ], "destination" : [ "out-info", 0 ] } }
		]
	}
}
