{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{ "major" : 9, "minor" : 1, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
		"classnamespace" : "box",
		"rect" : [ 80.0, 80.0, 980.0, 680.0 ],
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"boxes" : [
			{ "box" : { "id" : "in-bins", "maxclass" : "inlet", "numinlets" : 0, "numoutlets" : 1, "outlettype" : [ "" ],
				"patching_rect" : [ 30.0, 20.0, 30.0, 30.0 ], "comment" : "raw 8-bin list from fh.audio_bins" } },
			{ "box" : { "id" : "in-attack", "maxclass" : "inlet", "numinlets" : 0, "numoutlets" : 1, "outlettype" : [ "" ],
				"patching_rect" : [ 80.0, 20.0, 30.0, 30.0 ], "comment" : "attack ms (float)" } },
			{ "box" : { "id" : "in-release", "maxclass" : "inlet", "numinlets" : 0, "numoutlets" : 1, "outlettype" : [ "" ],
				"patching_rect" : [ 130.0, 20.0, 30.0, 30.0 ], "comment" : "release ms (float)" } },
			{ "box" : { "id" : "out-bins", "maxclass" : "outlet", "numinlets" : 1, "numoutlets" : 0,
				"patching_rect" : [ 30.0, 620.0, 30.0, 30.0 ], "comment" : "ASR+Brownian-modulated 8-bin list" } },

			{ "box" : { "id" : "title", "maxclass" : "comment",
				"patching_rect" : [ 30.0, 60.0, 760.0, 22.0 ], "fontsize" : 14.0,
				"text" : "fh.organic_mod : nervous-system modulation. ASR envelope + Brownian jitter on 8 bins.", "numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "unpack-in", "maxclass" : "newobj", "numinlets":1, "numoutlets":8,
				"outlettype" : [ "", "", "", "", "", "", "", "" ],
				"patching_rect" : [ 30.0, 110.0, 500.0, 22.0 ], "text" : "unpack 0. 0. 0. 0. 0. 0. 0. 0." } },

			{ "box" : { "id" : "thresh-0", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 30.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-1", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 95.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-2", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 160.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-3", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 225.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-4", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 290.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-5", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 355.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-6", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 420.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },
			{ "box" : { "id" : "thresh-7", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 485.0, 140.0, 60.0, 22.0 ], "text" : "> 0.15" } },

			{ "box" : { "id" : "env-0", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 30.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 8 80 0.8 400" } },
			{ "box" : { "id" : "env-1", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 95.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 8 80 0.8 500" } },
			{ "box" : { "id" : "env-2", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 160.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 10 120 0.7 600" } },
			{ "box" : { "id" : "env-3", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 225.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 12 150 0.6 700" } },
			{ "box" : { "id" : "env-4", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 290.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 12 150 0.6 700" } },
			{ "box" : { "id" : "env-5", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 355.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 6 90 0.5 450" } },
			{ "box" : { "id" : "env-6", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 420.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 5 70 0.4 350" } },
			{ "box" : { "id" : "env-7", "maxclass" : "newobj", "numinlets":1, "numoutlets":2,
				"outlettype" : [ "signal", "bang" ],
				"patching_rect" : [ 485.0, 170.0, 65.0, 22.0 ], "text" : "adsr~ 10 120 0.75 800" } },

			{ "box" : { "id" : "snap-clock", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 30.0, 205.0, 80.0, 22.0 ], "text" : "metro 25" } },
			{ "box" : { "id" : "clock-tgl", "maxclass" : "toggle", "numinlets":1, "numoutlets":1, "outlettype":["int"],
				"patching_rect" : [ 5.0, 205.0, 22.0, 22.0 ] } },
			{ "box" : { "id" : "tgl-load", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 5.0, 180.0, 50.0, 22.0 ], "text" : "loadbang" } },
			{ "box" : { "id" : "tgl-one", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 60.0, 180.0, 30.0, 22.0 ], "text" : "1" } },

			{ "box" : { "id" : "snap-0", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-1", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 95.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-2", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 160.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-3", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 225.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-4", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 290.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-5", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 355.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-6", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 420.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },
			{ "box" : { "id" : "snap-7", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 485.0, 230.0, 65.0, 22.0 ], "text" : "snapshot~ 25" } },

			{ "box" : { "id" : "cmt-brown", "maxclass" : "comment",
				"patching_rect" : [ 30.0, 265.0, 600.0, 22.0 ],
				"text" : "Brownian drift per bin (velocity + decay) - keeps things breathing even in silence.",
				"numinlets":1, "numoutlets":0 } },

			{ "box" : { "id" : "brown", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 290.0, 180.0, 22.0 ], "text" : "jit.bfg @basis simplex.noise @dim 8 8" } },
			{ "box" : { "id" : "brown-drive", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":["bang"],
				"patching_rect" : [ 220.0, 290.0, 80.0, 22.0 ], "text" : "qmetro 60" } },
			{ "box" : { "id" : "brown-offs", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 310.0, 290.0, 80.0, 22.0 ], "text" : "counter 0 10000" } },
			{ "box" : { "id" : "brown-msg", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 400.0, 290.0, 120.0, 22.0 ], "text" : "offset 0 $1 0 0" } },
			{ "box" : { "id" : "brown-grab", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 320.0, 180.0, 22.0 ], "text" : "jit.spill @plane 0" } },
			{ "box" : { "id" : "brown-route", "maxclass" : "newobj", "numinlets":1, "numoutlets":2, "outlettype":["", ""],
				"patching_rect" : [ 30.0, 350.0, 260.0, 22.0 ], "text" : "zl.slice 8" } },
			{ "box" : { "id" : "brown-scale", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 380.0, 260.0, 22.0 ], "text" : "vexpr ($f1 - 0.5) * 0.6" } },

			{ "box" : { "id" : "mod-merge", "maxclass" : "newobj", "numinlets":8, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 470.0, 500.0, 22.0 ], "text" : "pak 0. 0. 0. 0. 0. 0. 0. 0." } },

			{ "box" : { "id" : "env-unpack", "maxclass" : "newobj", "numinlets":1, "numoutlets":8, "outlettype":["","","","","","","",""],
				"patching_rect" : [ 30.0, 440.0, 500.0, 22.0 ], "text" : "unpack 0. 0. 0. 0. 0. 0. 0. 0." } },

			{ "box" : { "id" : "env-pak", "maxclass" : "newobj", "numinlets":8, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 410.0, 500.0, 22.0 ], "text" : "pak 0. 0. 0. 0. 0. 0. 0. 0." } },

			{ "box" : { "id" : "sum", "maxclass" : "newobj", "numinlets":1, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 500.0, 500.0, 22.0 ], "text" : "vexpr clip($f1 + $f2 * 0.25, 0., 4.)" } },

			{ "box" : { "id" : "level-1", "maxclass" : "newobj", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 30.0, 530.0, 120.0, 22.0 ], "text" : "pak 1. 2." } },
			{ "box" : { "id" : "level-msg", "maxclass" : "message", "numinlets":2, "numoutlets":1, "outlettype":[""],
				"patching_rect" : [ 165.0, 530.0, 180.0, 22.0 ], "text" : "$1 10." } },

			{ "box" : { "id" : "cmt-final", "maxclass" : "comment",
				"patching_rect" : [ 30.0, 570.0, 800.0, 40.0 ],
				"text" : "Output is the post-envelope, post-drift 8-bin list. Pipe to fh.inject via 'bins' message. Even silence keeps a low breathing motion through Brownian drift.",
				"numinlets":1, "numoutlets":0 } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "tgl-load", 0 ], "destination" : [ "tgl-one", 0 ] } },
			{ "patchline" : { "source" : [ "tgl-one", 0 ], "destination" : [ "clock-tgl", 0 ] } },
			{ "patchline" : { "source" : [ "clock-tgl", 0 ], "destination" : [ "snap-clock", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-0", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-1", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-2", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-3", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-4", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-5", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-6", 0 ] } },
			{ "patchline" : { "source" : [ "snap-clock", 0 ], "destination" : [ "snap-7", 0 ] } },

			{ "patchline" : { "source" : [ "in-bins", 0 ], "destination" : [ "unpack-in", 0 ] } },

			{ "patchline" : { "source" : [ "unpack-in", 0 ], "destination" : [ "thresh-0", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 1 ], "destination" : [ "thresh-1", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 2 ], "destination" : [ "thresh-2", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 3 ], "destination" : [ "thresh-3", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 4 ], "destination" : [ "thresh-4", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 5 ], "destination" : [ "thresh-5", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 6 ], "destination" : [ "thresh-6", 0 ] } },
			{ "patchline" : { "source" : [ "unpack-in", 7 ], "destination" : [ "thresh-7", 0 ] } },

			{ "patchline" : { "source" : [ "thresh-0", 0 ], "destination" : [ "env-0", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-1", 0 ], "destination" : [ "env-1", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-2", 0 ], "destination" : [ "env-2", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-3", 0 ], "destination" : [ "env-3", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-4", 0 ], "destination" : [ "env-4", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-5", 0 ], "destination" : [ "env-5", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-6", 0 ], "destination" : [ "env-6", 0 ] } },
			{ "patchline" : { "source" : [ "thresh-7", 0 ], "destination" : [ "env-7", 0 ] } },

			{ "patchline" : { "source" : [ "env-0", 0 ], "destination" : [ "snap-0", 0 ] } },
			{ "patchline" : { "source" : [ "env-1", 0 ], "destination" : [ "snap-1", 0 ] } },
			{ "patchline" : { "source" : [ "env-2", 0 ], "destination" : [ "snap-2", 0 ] } },
			{ "patchline" : { "source" : [ "env-3", 0 ], "destination" : [ "snap-3", 0 ] } },
			{ "patchline" : { "source" : [ "env-4", 0 ], "destination" : [ "snap-4", 0 ] } },
			{ "patchline" : { "source" : [ "env-5", 0 ], "destination" : [ "snap-5", 0 ] } },
			{ "patchline" : { "source" : [ "env-6", 0 ], "destination" : [ "snap-6", 0 ] } },
			{ "patchline" : { "source" : [ "env-7", 0 ], "destination" : [ "snap-7", 0 ] } },

			{ "patchline" : { "source" : [ "snap-0", 0 ], "destination" : [ "env-pak", 0 ] } },
			{ "patchline" : { "source" : [ "snap-1", 0 ], "destination" : [ "env-pak", 1 ] } },
			{ "patchline" : { "source" : [ "snap-2", 0 ], "destination" : [ "env-pak", 2 ] } },
			{ "patchline" : { "source" : [ "snap-3", 0 ], "destination" : [ "env-pak", 3 ] } },
			{ "patchline" : { "source" : [ "snap-4", 0 ], "destination" : [ "env-pak", 4 ] } },
			{ "patchline" : { "source" : [ "snap-5", 0 ], "destination" : [ "env-pak", 5 ] } },
			{ "patchline" : { "source" : [ "snap-6", 0 ], "destination" : [ "env-pak", 6 ] } },
			{ "patchline" : { "source" : [ "snap-7", 0 ], "destination" : [ "env-pak", 7 ] } },

			{ "patchline" : { "source" : [ "env-pak", 0 ], "destination" : [ "env-unpack", 0 ] } },

			{ "patchline" : { "source" : [ "brown-drive", 0 ], "destination" : [ "brown-offs", 0 ] } },
			{ "patchline" : { "source" : [ "brown-offs", 0 ], "destination" : [ "brown-msg", 0 ] } },
			{ "patchline" : { "source" : [ "brown-msg", 0 ], "destination" : [ "brown", 0 ] } },
			{ "patchline" : { "source" : [ "brown", 0 ], "destination" : [ "brown-grab", 0 ] } },
			{ "patchline" : { "source" : [ "brown-grab", 0 ], "destination" : [ "brown-route", 0 ] } },
			{ "patchline" : { "source" : [ "brown-route", 0 ], "destination" : [ "brown-scale", 0 ] } },

			{ "patchline" : { "source" : [ "env-pak", 0 ], "destination" : [ "sum", 0 ] } },
			{ "patchline" : { "source" : [ "brown-scale", 0 ], "destination" : [ "sum", 0 ] } },
			{ "patchline" : { "source" : [ "sum", 0 ], "destination" : [ "out-bins", 0 ] } },

			{ "patchline" : { "source" : [ "in-attack", 0 ], "destination" : [ "level-msg", 0 ] } },
			{ "patchline" : { "source" : [ "in-release", 0 ], "destination" : [ "level-msg", 0 ] } },
			{ "patchline" : { "source" : [ "level-msg", 0 ], "destination" : [ "env-0", 0 ] } }
		]
	}
}
